#!/usr/bin/awk -f

BEGIN {
    nr = 0;
    na1 = 0;
    na2 = 0;
    na3 = 0;
    na4 = 0;
}

/INFO/ && /RF/ && (/Buy/ || /Sell/) {
    nr += 1;
    rf[nr] = $0;
}

/INFO/ && /RF Cash/ {
    cr = $7;
}

/INFO/ && /ATR/ && (/Buy/ || /Sell/) {
    na1 += 1;
    atr1[na] = $0;
}

/INFO/ && /ATR1 Cash/ {
    ca1 = $7;
}

/INFO/ && /ATR2/ && (/Buy/ || /Sell/) {
    na2 += 1;
    atr2[na] = $0;
}

/INFO/ && /ATR2 Cash/ {
    ca2 = $7;
}

/INFO/ && /ATR3/ && (/Buy/ || /Sell/) {
    na3 += 1;
    atr3[na] = $0;
}

/INFO/ && /ATR3 Cash/ {
    ca3 = $7;
}

/INFO/ && /ATR4/ && (/Buy/ || /Sell/) {
    na4 += 1;
    atr2[na] = $0;
}

/INFO/ && /ATR4 Cash/ {
    ca4 = $7;
}

END {
    print "========================"
    print "No. of RF   trades: " nr;
    print "No. of ATR1 trades: " na1;
    print "No. of ATR2 trades: " na2;
    print "No. of ATR3 trades: " na3;
    print "No. of ATR4 trades: " na4;
    print ""
    print "RF   cash: " cr;
    print "ATR1 cash: " ca1;
    print "ATR2 cash: " ca2;
    print "ATR3 cash: " ca3;
    print "ATR4 cash: " ca4;
    print "========================"
}
