version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      # specify the python version
      - image: circleci/python:3.6.7
    steps:
      - checkout
      # download and cache the virtualenv
      - restore_cache:
          keys:
            - venv-{{ .Branch }}-{{ checksum "setup.py" }}
            - venv-{{ .Branch }}-
            - venv-
      - run:
          name: Install virtualenv
          command: |
            pip install -q --user virtualenv
      - run:
          name: Actvate virtualenv and install dependencies
          command: make initial-python-setup
      - save_cache:
          key: venv-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - ".venv"
            - "~/.local/lib/python3.6"
      - run:
          name: Run unit tests
          command: |
            source .venv/bin/activate
            pytest --junitxml=test-results/results.xml test/unit
      - run:
          name: Run linter
          command: |
            source .venv/bin/activate
            pylint --exit-zero cryptle
      - run:
          name: Check formatting
          command: |
            source .venv/bin/activate
            black --check cryptle
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test
